"""empty message

Revision ID: 2082777967e5
Revises: 
Create Date: 2021-01-06 09:42:29.599046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2082777967e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessao',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contato_id', sa.BigInteger(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('finalizada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contato_id'], ['contato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sessao_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('destinatario_eh_sistema', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao.id'], ),
    sa.PrimaryKeyConstraint('id', 'sessao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    op.drop_table('sessao')
    op.drop_table('contato')
    # ### end Alembic commands ###
