"""empty message

Revision ID: a7bf876df1b7
Revises: 2082777967e5
Create Date: 2021-01-06 13:38:53.596067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bf876df1b7'
down_revision = '2082777967e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contato', sa.Column('qr_code', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contato', 'qr_code')
    # ### end Alembic commands ###
